# Generated by Django 5.2.7 on 2026-05-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0003_alter_address_id_alter_brand_id_alter_brand_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('MENS', 'Mens'), ('WOMENS', 'Womens'), ('NEUTRAL', 'Neutral')], default='NEUTRAL', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
