# Generated by Django 5.2.7 on 2026-05-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0004_product_gender_product_is_trending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
    ]
