# Generated by Django 5.2.7 on 2026-05-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0005_remove_gender_from_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
