# Generated by Django 5.2.7 on 2026-05-14 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0006_remove_product_brand_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageImage',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='stock',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock_status',
            field=models.CharField(choices=[('IN_STOCK', 'In Stock'), ('OUT_OF_STOCK', 'Out Of Stock'), ('LIMITED', 'Limited')], default='IN_STOCK', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('IN_STOCK', 'In Stock'), ('OUT_OF_STOCK', 'Out Of Stock'), ('LIMITED', 'Limited')], default='OUT_OF_STOCK', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
