# Generated by Django 5.2.7 on 2026-05-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0008_alter_productvariant_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('XM', 'XM'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('CUSTOM', 'Custom size')], default='M', max_length=20),
        ),
    ]
