# Generated by Django 5.2.7 on 2026-05-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0009_alter_productvariant_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Shirt', 'Shirt'), ('Pant', 'Pant'), ('Shorts & Track', 'Shorts & Track'), ('T-shirt', 'T-shirt')], default='Shirt', max_length=50),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(choices=[('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('4XL', '4XL'), ('5XL', '5XL'), ('28', '28'), ('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('40', '40'), ('42', '42'), ('44', '44'), ('CUSTOM', 'Custom size')], default='M', max_length=20),
        ),
    ]
