# Generated by Django 5.2.7 on 2026-05-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0010_product_product_type_alter_productvariant_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('IN_STOCK', 'In Stock'), ('OUT_OF_STOCK', 'Out Of Stock'), ('LIMITED', 'Limited')], default='IN_STOCK', max_length=20),
        ),
    ]
