# Generated by Django 5.2.7 on 2026-05-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0012_product_image_productvariant_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no_variant',
            field=models.BooleanField(default=False, verbose_name='No variant'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
