# Generated by Django 5.2.7 on 2026-05-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0013_product_no_variant_productvariant_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='allow_discount',
            field=models.BooleanField(default=False, verbose_name='Allow discount'),
        ),
    ]
