# Generated by Django 5.2.7 on 2026-05-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0014_productvariant_allow_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='allow_discount',
            field=models.BooleanField(default=True, verbose_name='Allow discount'),
        ),
    ]
