# Generated by Django 5.2.7 on 2026-05-18 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0015_alter_productvariant_allow_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='no_variant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_status',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='sku',
        ),
    ]
