# Generated by Django 5.2.7 on 2026-05-18 12:16

import fashion.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0016_remove_product_no_variant_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line',
            field=fashion.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=fashion.fields.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=fashion.fields.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='address',
            name='full_name',
            field=fashion.fields.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=fashion.fields.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=fashion.fields.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=fashion.fields.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=fashion.fields.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=fashion.fields.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=fashion.fields.EncryptedCharField(blank=True, max_length=500),
        ),
    ]
