# Generated by Django 5.2.7 on 2026-05-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0017_alter_address_address_line_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'color', 'size')},
        ),
    ]
