# Generated by Django 5.2.7 on 2026-05-20 12:36

import django.contrib.postgres.fields
from django.db import migrations, models


def consolidate_variants(apps, schema_editor):
    ProductVariant = apps.get_model('fashion', 'ProductVariant')
    variants = ProductVariant.objects.all()
    duplicates = {}
    for var in variants:
        key = (var.product_id, var.color)
        if key not in duplicates:
            duplicates[key] = []
        duplicates[key].append(var)
        
    for key, var_list in duplicates.items():
        first_variant = var_list[0]
        sizes = set()
        total_stock = 0
        for var in var_list:
            if var.size:
                sizes.add(var.size)
            total_stock += var.stock
            
        first_variant.sizes = list(sizes)
        first_variant.stock = total_stock
        first_variant.save()
        
        for var in var_list[1:]:
            var.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0018_alter_productvariant_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sizes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('4XL', '4XL'), ('5XL', '5XL'), ('28', '28'), ('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('40', '40'), ('42', '42'), ('44', '44'), ('CUSTOM', 'Custom size')], max_length=20), blank=True, default=list, size=None),
        ),
        migrations.RunPython(consolidate_variants, reverse_code=migrations.RunPython.noop),
    ]
