# Generated by Django 5.2.7 on 2026-05-20 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0019_alter_productvariant_unique_together_cartitem_size_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'color')},
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
    ]
