# Generated by Django

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0020_alter_productvariant_unique_together_and_more'),
    ]

    operations = [
        # 1. Drop existing unique_together constraint on ('product', 'color')
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
        # 2. Create model ProductVariantImage
        migrations.CreateModel(
            name='ProductVariantImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_images', to='fashion.product')),
            ],
            options={
                'unique_together': {('product', 'color')},
            },
        ),
        # 3. Add field size to ProductVariant as nullable CharField
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('5XL', '5XL'), ('28', '28'), ('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('40', '40'), ('42', '42'), ('44', '44')], max_length=20, null=True),
        ),
    ]
