# Generated by Django

from django.db import migrations, models


def split_variants_and_migrate_images(apps, schema_editor):
    ProductVariant = apps.get_model('fashion', 'ProductVariant')
    ProductVariantImage = apps.get_model('fashion', 'ProductVariantImage')
    CartItem = apps.get_model('fashion', 'CartItem')
    OrderItem = apps.get_model('fashion', 'OrderItem')

    # 1. First migrate images
    for var in ProductVariant.objects.all():
        if var.image:
            ProductVariantImage.objects.get_or_create(
                product=var.product,
                color=var.color,
                defaults={'image': var.image}
            )

    # 2. Split multi-size variants
    for var in list(ProductVariant.objects.all()):
        # Retrieve sizes array
        sizes = getattr(var, 'sizes', [])
        # Fallback choices if sizes array is empty
        if not sizes:
            p_type = var.product.product_type
            rules = {
                'Shirt': ['M', 'L', 'XL', '2XL'],
                'Pant': ['28', '30', '32', '34', '36', '40', '42', '44'],
                'Shorts & Track': ['M', 'L', 'XL', '2XL', '3XL', '5XL'],
                'T-shirt': ['M', 'L', 'XL', '2XL', '3XL', '5XL'],
            }
            allowed = rules.get(p_type, [])
            sizes = [allowed[0]] if allowed else ['M']

        # Set first size on the current row
        first_size = sizes[0]
        old_variant_id = var.id
        var.size = first_size
        var.save()

        # For remaining sizes, duplicate the variant and remap relations
        for size_val in sizes[1:]:
            new_var = ProductVariant.objects.create(
                product=var.product,
                color=var.color,
                stock=var.stock,
                price=var.price,
                stock_status=var.stock_status,
                is_active=var.is_active,
                allow_discount=var.allow_discount,
                size=size_val
            )
            # Remap CartItem
            CartItem.objects.filter(product_variant_id=old_variant_id, size=size_val).update(product_variant=new_var)
            # Remap OrderItem
            OrderItem.objects.filter(product_variant_id=old_variant_id, size=size_val).update(product_variant=new_var)


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0021_pre_variant_migration'),
    ]

    operations = [
        migrations.RunPython(split_variants_and_migrate_images, reverse_code=migrations.RunPython.noop),
    ]
