# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0022_data_variant_migration'),
    ]

    operations = [
        # 1. Remove field image from ProductVariant
        migrations.RemoveField(
            model_name='productvariant',
            name='image',
        ),
        # 2. Remove field sizes from ProductVariant
        migrations.RemoveField(
            model_name='productvariant',
            name='sizes',
        ),
        # 3. Alter size field to be non-nullable
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(choices=[('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('5XL', '5XL'), ('28', '28'), ('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('40', '40'), ('42', '42'), ('44', '44')], max_length=20),
        ),
        # 4. Set unique_together to {('product', 'color', 'size')}
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'color', 'size')},
        ),
    ]
